name: text_editor_CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: Run tests
        run: |
          go test ./... -v
          go test ./pkg/buffer -fuzz=Fuzz -fuzztime=30s -v
